// Generated by scripts/sync_media.py from public/work and public/icons. Do not edit by hand.
export type Media = { cover?: string; night?: string; shots?: string[]; trailer?: string; poster?: string; icon?: string };
export const MEDIA: Record<string, Media> = {
    "adpulse": {
        "shots": [
            "/work/adpulse-2.jpg"
        ],
        "cover": "/work/adpulse.jpg",
        "icon": "/icons/adpulse.webp"
    },
    "article-iii": {
        "shots": [
            "/work/article-iii-2.jpg",
            "/work/article-iii-3.jpg"
        ],
        "cover": "/work/article-iii.jpg"
    },
    "cgs-language-services": {
        "shots": [
            "/work/cgs-language-services-2.jpg",
            "/work/cgs-language-services-3.jpg"
        ],
        "cover": "/work/cgs-language-services.jpg"
    },
    "china-global-study": {
        "shots": [
            "/work/china-global-study-2.jpg"
        ],
        "cover": "/work/china-global-study.jpg"
    },
    "china-global-travel": {
        "shots": [
            "/work/china-global-travel-2.jpg",
            "/work/china-global-travel-3.jpg"
        ],
        "cover": "/work/china-global-travel.jpg"
    },
    "click2minimize": {
        "cover": "/work/click2minimize.jpg",
        "icon": "/icons/click2minimize.webp"
    },
    "cloneos": {
        "shots": [
            "/work/cloneos-2.jpg"
        ],
        "cover": "/work/cloneos.jpg"
    },
    "deck": {
        "shots": [
            "/work/deck-2.jpg"
        ],
        "cover": "/work/deck.jpg",
        "icon": "/icons/deck.webp"
    },
    "echoscribe": {
        "cover": "/work/echoscribe.jpg"
    },
    "eli": {
        "shots": [
            "/work/eli-2.jpg",
            "/work/eli-3.jpg"
        ],
        "cover": "/work/eli.jpg",
        "icon": "/icons/eli.webp"
    },
    "estelle": {
        "poster": "/work/estelle-poster.jpg",
        "trailer": "/work/estelle.mp4",
        "icon": "/icons/estelle.webp"
    },
    "fader": {
        "cover": "/work/fader.jpg",
        "icon": "/icons/fader.webp"
    },
    "fortress": {
        "cover": "/work/fortress.jpg"
    },
    "freelane": {
        "shots": [
            "/work/freelane-2.jpg"
        ],
        "cover": "/work/freelane.jpg"
    },
    "gopilates": {
        "poster": "/work/gopilates-poster.jpg",
        "cover": "/work/gopilates.jpg",
        "trailer": "/work/gopilates.mp4",
        "icon": "/icons/gopilates.webp"
    },
    "hope-hr": {
        "shots": [
            "/work/hope-hr-2.jpg",
            "/work/hope-hr-3.jpg"
        ],
        "cover": "/work/hope-hr.jpg"
    },
    "hope-ledger": {
        "cover": "/work/hope-ledger.jpg"
    },
    "infinitecs": {
        "shots": [
            "/work/infinitecs-2.jpg",
            "/work/infinitecs-3.jpg"
        ],
        "cover": "/work/infinitecs.jpg"
    },
    "leadsniper": {
        "shots": [
            "/work/leadsniper-2.jpg",
            "/work/leadsniper-3.jpg"
        ],
        "cover": "/work/leadsniper.jpg"
    },
    "lessonforge": {
        "shots": [
            "/work/lessonforge-2.jpg"
        ],
        "cover": "/work/lessonforge.jpg"
    },
    "lorani": {
        "shots": [
            "/work/lorani-2.jpg"
        ],
        "cover": "/work/lorani.jpg"
    },
    "lumi": {
        "shots": [
            "/work/lumi-2.jpg",
            "/work/lumi-3.jpg"
        ],
        "cover": "/work/lumi.jpg"
    },
    "maison-brume": {
        "shots": [
            "/work/maison-brume-2.jpg",
            "/work/maison-brume-3.jpg"
        ],
        "cover": "/work/maison-brume.jpg"
    },
    "mcallister-gallery": {
        "shots": [
            "/work/mcallister-gallery-2.jpg",
            "/work/mcallister-gallery-3.jpg"
        ],
        "cover": "/work/mcallister-gallery.jpg"
    },
    "nabil-portfolio": {
        "shots": [
            "/work/nabil-portfolio-2.jpg",
            "/work/nabil-portfolio-3.jpg"
        ],
        "cover": "/work/nabil-portfolio.jpg"
    },
    "night-market-tycoon": {
        "shots": [
            "/work/night-market-tycoon-2.jpg",
            "/work/night-market-tycoon-3.jpg"
        ],
        "cover": "/work/night-market-tycoon.jpg"
    },
    "nota-parfum": {
        "shots": [
            "/work/nota-parfum-2.jpg",
            "/work/nota-parfum-3.jpg"
        ],
        "cover": "/work/nota-parfum.jpg"
    },
    "pause": {
        "cover": "/work/pause.jpg",
        "icon": "/icons/pause.webp"
    },
    "practicesync": {
        "shots": [
            "/work/practicesync-2.jpg",
            "/work/practicesync-3.jpg"
        ],
        "night": "/work/practicesync-night.jpg",
        "poster": "/work/practicesync-poster.jpg",
        "cover": "/work/practicesync.jpg",
        "trailer": "/work/practicesync.mp4",
        "icon": "/icons/practicesync.webp"
    },
    "relay": {
        "cover": "/work/relay.jpg",
        "icon": "/icons/relay.webp"
    },
    "rudratek-dashboard": {
        "shots": [
            "/work/rudratek-dashboard-2.jpg",
            "/work/rudratek-dashboard-3.jpg"
        ],
        "cover": "/work/rudratek-dashboard.jpg"
    },
    "scriptdeck": {
        "shots": [
            "/work/scriptdeck-2.jpg"
        ],
        "cover": "/work/scriptdeck.jpg"
    },
    "strata-triage": {
        "shots": [
            "/work/strata-triage-2.jpg",
            "/work/strata-triage-3.jpg"
        ],
        "cover": "/work/strata-triage.jpg"
    },
    "studioos": {
        "shots": [
            "/work/studioos-2.jpg",
            "/work/studioos-3.jpg"
        ],
        "cover": "/work/studioos.jpg"
    },
    "sunz": {
        "shots": [
            "/work/sunz-2.jpg"
        ],
        "cover": "/work/sunz.jpg",
        "icon": "/icons/sunz.webp"
    },
    "together-tasks": {
        "shots": [
            "/work/together-tasks-2.jpg",
            "/work/together-tasks-3.jpg"
        ],
        "cover": "/work/together-tasks.jpg"
    },
    "tryit": {
        "shots": [
            "/work/tryit-2.jpg"
        ],
        "cover": "/work/tryit.jpg",
        "icon": "/icons/tryit.webp"
    },
    "viralos": {
        "shots": [
            "/work/viralos-2.jpg"
        ],
        "cover": "/work/viralos.jpg"
    },
    "virtual-tryon-poc": {
        "shots": [
            "/work/virtual-tryon-poc-2.jpg"
        ],
        "cover": "/work/virtual-tryon-poc.jpg"
    }
};
