// Generated by scripts/sync_media.py from public/work and public/icons. Do not edit by hand.
export type Media = { cover?: string; night?: string; shots?: string[]; trailer?: string; poster?: string; icon?: string };
export const MEDIA: Record<string, Media> = {
    "adpulse": {
        "shots": [
            "/work/adpulse-2.jpg"
        ],
        "cover": "/work/adpulse.jpg",
        "icon": "/icons/adpulse.webp"
    },
    "article-iii": {
        "shots": [
            "/work/article-iii-2.jpg",
            "/work/article-iii-3.jpg"
        ],
        "cover": "/work/article-iii.jpg"
    },
    "cgs-language-services": {
        "shots": [
            "/work/cgs-language-services-2.jpg",
            "/work/cgs-language-services-3.jpg"
        ],
        "cover": "/work/cgs-language-services.jpg"
    },
    "china-global-travel": {
        "shots": [
            "/work/china-global-travel-2.jpg",
            "/work/china-global-travel-3.jpg"
        ],
        "cover": "/work/china-global-travel.jpg"
    },
    "echoscribe": {
        "cover": "/work/echoscribe.jpg"
    },
    "estelle": {
        "poster": "/work/estelle-poster.jpg",
        "trailer": "/work/estelle.mp4",
        "icon": "/icons/estelle.webp"
    },
    "fortress": {
        "cover": "/work/fortress.jpg"
    },
    "gopilates": {
        "poster": "/work/gopilates-poster.jpg",
        "cover": "/work/gopilates.jpg",
        "trailer": "/work/gopilates.mp4",
        "icon": "/icons/gopilates.webp"
    },
    "infinitecs": {
        "shots": [
            "/work/infinitecs-2.jpg",
            "/work/infinitecs-3.jpg"
        ],
        "cover": "/work/infinitecs.jpg"
    },
    "leadsniper": {
        "shots": [
            "/work/leadsniper-2.jpg",
            "/work/leadsniper-3.jpg"
        ],
        "cover": "/work/leadsniper.jpg"
    },
    "lessonforge": {
        "shots": [
            "/work/lessonforge-2.jpg",
            "/work/lessonforge-3.jpg"
        ],
        "cover": "/work/lessonforge.jpg"
    },
    "lorani": {
        "shots": [
            "/work/lorani-2.jpg",
            "/work/lorani-3.jpg"
        ],
        "cover": "/work/lorani.jpg"
    },
    "maison-brume": {
        "shots": [
            "/work/maison-brume-2.jpg",
            "/work/maison-brume-3.jpg"
        ],
        "cover": "/work/maison-brume.jpg"
    },
    "mcallister-gallery": {
        "shots": [
            "/work/mcallister-gallery-2.jpg",
            "/work/mcallister-gallery-3.jpg"
        ],
        "cover": "/work/mcallister-gallery.jpg"
    },
    "nabil-portfolio": {
        "shots": [
            "/work/nabil-portfolio-2.jpg",
            "/work/nabil-portfolio-3.jpg"
        ],
        "cover": "/work/nabil-portfolio.jpg"
    },
    "night-market-tycoon": {
        "shots": [
            "/work/night-market-tycoon-2.jpg",
            "/work/night-market-tycoon-3.jpg"
        ],
        "cover": "/work/night-market-tycoon.jpg"
    },
    "nota-parfum": {
        "shots": [
            "/work/nota-parfum-2.jpg",
            "/work/nota-parfum-3.jpg"
        ],
        "cover": "/work/nota-parfum.jpg"
    },
    "practicesync": {
        "night": "/work/practicesync-night.jpg",
        "cover": "/work/practicesync.jpg",
        "icon": "/icons/practicesync.webp"
    },
    "rudratek-dashboard": {
        "shots": [
            "/work/rudratek-dashboard-2.jpg",
            "/work/rudratek-dashboard-3.jpg"
        ],
        "cover": "/work/rudratek-dashboard.jpg"
    },
    "scriptdeck": {
        "shots": [
            "/work/scriptdeck-2.jpg"
        ],
        "cover": "/work/scriptdeck.jpg"
    },
    "strata-triage": {
        "shots": [
            "/work/strata-triage-2.jpg",
            "/work/strata-triage-3.jpg"
        ],
        "cover": "/work/strata-triage.jpg"
    },
    "tryit": {
        "shots": [
            "/work/tryit-2.jpg"
        ],
        "cover": "/work/tryit.jpg",
        "icon": "/icons/tryit.webp"
    },
    "viralos": {
        "shots": [
            "/work/viralos-2.jpg"
        ],
        "cover": "/work/viralos.jpg"
    },
    "virtual-tryon-poc": {
        "shots": [
            "/work/virtual-tryon-poc-2.jpg"
        ],
        "cover": "/work/virtual-tryon-poc.jpg"
    },
    "click2minimize": {
        "icon": "/icons/click2minimize.webp"
    },
    "deck": {
        "icon": "/icons/deck.webp"
    },
    "eli": {
        "icon": "/icons/eli.webp"
    },
    "fader": {
        "icon": "/icons/fader.webp"
    },
    "pause": {
        "icon": "/icons/pause.webp"
    },
    "relay": {
        "icon": "/icons/relay.webp"
    },
    "sunz": {
        "icon": "/icons/sunz.webp"
    }
};
