export interface Project {
    id: string;
    slug: string;
    title: string;
    description: string;
    longDescription: string;
    tech: string[];
    metrics: { label: string; value: string }[];
    color: string;
    textColor: string;
    /** GitHub repo URL (or wherever the source canonically lives). */
    link: string;
    /** Live demo / production URL (Vercel, GH Pages, App Store, etc.). */
    liveDemo?: string;
    /** Apple App Store listing URL. */
    appStore?: string;
    /** Private commercial repo — hides the "View Code" link. */
    private?: boolean;
    category: string;
    problem: string;
    solution: string;
    outcomes: string[];
}

// All entries verified against live GitHub metadata + repo READMEs.
// Refreshed 2026-05-11 after a portfolio-wide GitHub sync.

export const projects: Project[] = [
    /* ─────────── TIER A · APP STORE / SHIPPED COMMERCIAL ─────────── */

    {
        id: "001",
        slug: "tryit",
        title: "TryIt",
        description: "AI virtual try-on for iPhone. See clothes on you before you buy. SwiftUI · iOS 18 · Gemini 3 Flash Image · RevenueCat. Live on the App Store.",
        longDescription: "A native iPhone app that composites clothing onto the user's selfie via Gemini 3 Flash Image. Three input modes (paste a product URL, share a screenshot via the system Share Sheet, or point the camera at a tag), a two-stage AI pipeline (a cheap Gemini 2.5 Flash validation pass before the expensive image-gen call), an 8-screen onboarding funnel tuned for conversion, RevenueCat-managed subscriptions, a Lock-Screen widget showing the latest result, and a privacy posture Apple's review team has on file: photos never leave the device beyond the ephemeral AI request.",
        tech: ["SwiftUI", "iOS 18", "Gemini 3", "RevenueCat", "WidgetKit", "Share Extension", "XcodeGen"],
        metrics: [
            { label: "Status", value: "App Store" },
            { label: "Targets", value: "App + Widget + Share" },
            { label: "Code", value: "~9k Swift" },
        ],
        color: "bg-acid",
        textColor: "text-ink",
        link: "https://github.com/hatimhtm/tryit-ios",
        appStore: "https://apps.apple.com/app/id6761598749",
        private: true,
        category: "iOS",
        problem: "Online clothing returns are a $24B problem because people can't tell how a garment will look on them. Existing try-on tools either need a brand-specific integration or upload your face to a marketing CRM.",
        solution: "A single-tap iPhone app: drop in a product link or screenshot, the AI extracts the garment and composites it onto a reusable profile selfie. No account, no third-party upload beyond the ephemeral AI request. Three discovery surfaces (link / share / camera) cover every way a user encounters clothing in the wild.",
        outcomes: [
            "Shipped to the App Store (review-cleared on face-data + AVCaptureSession bug fix)",
            "Two-stage AI pipeline cuts cost on invalid inputs before the expensive generation step",
            "Widget + Share Extension turn the app into an OS-wide capability",
            "On-device-only photo storage — privacy posture documented to Apple Review",
        ],
    },
    {
        id: "002",
        slug: "gopilates",
        title: "GoPilates",
        description: "French-first Pilates iOS app on the App Store. ~13k LOC SwiftUI, 37-screen onboarding funnel, RevenueCat subscriptions, HealthKit, Lottie, Tenjin attribution. Freelance build.",
        longDescription: "A native iPhone Pilates app built as a freelance commission. iPhone-only on iOS 17+, French as the primary locale, a 37-screen onboarding funnel that culminates in a RevenueCat-managed paywall, HealthKit-backed workout tracking, Lottie animations across the empty-states, and Tenjin attribution wired into the install pipeline. Shipped to the App Store.",
        tech: ["SwiftUI", "iOS 17", "RevenueCat", "HealthKit", "Lottie", "Tenjin"],
        metrics: [
            { label: "Status", value: "App Store" },
            { label: "Onboarding", value: "37 screens" },
            { label: "Code", value: "~13k Swift" },
        ],
        color: "bg-hotpink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/gopilates-ios",
        appStore: "https://apps.apple.com/us/app/gopilates-app/id6760300479",
        category: "iOS",
        problem: "The Pilates studios + practitioners niche is underserved by generic fitness apps. The client needed an iPhone-only experience in French with a real paywall, native HealthKit integration, and an onboarding flow that actually converts.",
        solution: "Full SwiftUI build optimised for the iPhone form factor only (no iPad scaling compromise). RevenueCat handles the subscription state; HealthKit captures workouts to the system store; Lottie carries the editorial illustration moments; Tenjin wires the install attribution so the marketing spend is measurable.",
        outcomes: [
            "Shipped to the App Store under a custom no-resale license",
            "37-screen onboarding funnel tuned around the paywall conversion",
            "HealthKit + Lottie + Tenjin all wired into the native build",
            "iPhone-only — no iPad scaling compromise",
        ],
    },
    {
        id: "003",
        slug: "adpulse",
        title: "AdPulse",
        description: "Open-source iOS 17+ analytics dashboard for ad-creative performance. SwiftUI · Swift Charts · Live Activities · SwiftData · MVVM. Z-score anomaly detection.",
        longDescription: "AdPulse is an open-source iOS dashboard for tracking ad-creative performance. Modern SwiftUI on iOS 17+ with `@Observable`, SwiftData for persistence, Swift Charts for interactive ROAS/CPM/budget visualisations, Live Activities + Dynamic Island for at-a-glance campaign tracking, and a Z-score anomaly detector that surfaces creative regressions before the daily summary email.",
        tech: ["SwiftUI", "iOS 17", "SwiftData", "Swift Charts", "Live Activities", "Dynamic Island", "MVVM"],
        metrics: [
            { label: "Platform", value: "iOS 17+" },
            { label: "License", value: "MIT" },
            { label: "Anomalies", value: "Z-score" },
        ],
        color: "bg-electric",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/adpulse-ios",
        category: "iOS",
        problem: "Meta Ads / TikTok Ads web dashboards are dense and slow; the iOS operator wants a glance-able view between meetings. Existing native viewers are paid SaaS, not open-source.",
        solution: "A clean SwiftUI build using the iOS 17+ surface: `@Observable` view models, SwiftData persistence, Swift Charts for the bar/line/donut visualisations, Live Activities + Dynamic Island for campaigns under active watch, and a Z-score anomaly detector that catches creative regressions before the morning digest.",
        outcomes: [
            "Open-source under MIT — installable, forkable, learnable",
            "iOS 17+ feature stack (Live Activities, Dynamic Island, SwiftData, @Observable)",
            "Statistical anomaly detection inside the app, not as a server feature",
        ],
    },

    /* ─────────── TIER B · BIG SYSTEMS / TECHNICAL DEPTH ─────────── */

    {
        id: "004",
        slug: "viralos",
        title: "Viral OS",
        description: "AI command center for a portfolio of consumer iOS apps. Ingests App Store Connect, RevenueCat (101 webhook events), TikTok, ad spend — computes pLTV, cohort retention, app health, anomaly alerts.",
        longDescription: "Viral OS is the operations dashboard for a B2C app studio. It ingests App Store Connect (sales + metadata), RevenueCat (101 webhook event types), TikTok (via a Playwright scraper running on GitHub Actions, not the paid API), and manual ad spend; computes metrics that aren't in any individual tool — predicted LTV (geometric with realized-churn fallback), LTV/CAC, cohort retention, app-health score (0–100), lifecycle stage; and fires Slack/Discord/email alerts the same day a paywall regression or refund spike appears.",
        tech: ["Next.js 16", "Supabase", "Gemini 3 Pro", "RevenueCat", "App Store Connect", "Playwright", "Sentry"],
        metrics: [
            { label: "API Routes", value: "14" },
            { label: "Dashboard Pages", value: "19" },
            { label: "DB Migrations", value: "10" },
        ],
        color: "bg-electric",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/viralos",
        private: true,
        category: "AI / ML",
        problem: "Studios shipping a portfolio of apps lose hours every week stitching together RevenueCat, App Store Connect, TikTok analytics, and ad spend across separate dashboards. By the time a paywall regression shows up in a monthly review, the damage is done.",
        solution: "One Supabase-backed dashboard pulls every data source into a unified schema. Hand-rolled detectors (EWMA + 2σ on revenue + refunds + MRR drops + rating drops + rejected builds) catch anomalies same-day. Gemini 3 Pro is wired into every surface via tool-use, not stuffed context — the AI queries the live DB instead of getting fed it.",
        outcomes: [
            "Single dashboard replaces RevenueCat + ASC + TikTok + spreadsheet tabs",
            "Same-day anomaly alerts on Slack / Discord / email",
            "Predicted LTV + cohort retention + app-health score, all computed in-app",
            "Zero paid analytics SDK — every metric derived from raw events",
        ],
    },
    {
        id: "005",
        slug: "together-tasks",
        title: "Together Tasks",
        description: "AI-native task OS for couples. Type or speak a task — Gemini parses date / priority / urgency / duration. Real-time sync between two phones, routines, gamified streaks. Web + PWA + native Android via Capacitor.",
        longDescription: "Together Tasks turns natural language into structured shared tasks. Type \"buy rosemary tomorrow evening\" or hold the mic — Gemini 3 extracts the title, sets due to tomorrow 19:00, classifies urgency + importance + estimated duration, and decides whether to break the job into subtasks. Realtime Supabase channels keep both phones in sync. Routines (v2 flagship) live in a separate surface for repeatable habits with per-routine streaks and partner-completion bars. Web + installable PWA + native Android via Capacitor.",
        tech: ["Next.js 15", "Supabase Realtime", "Gemini 3", "Capacitor 8", "Tailwind 4", "Web Push", "Zustand"],
        metrics: [
            { label: "Platforms", value: "Web · PWA · Android" },
            { label: "TS Files", value: "80+" },
            { label: "Routes", value: "9 dashboard" },
        ],
        color: "bg-hotpink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/together-tasks",
        private: true,
        category: "AI / ML",
        problem: "Two-person households split tasks across iMessage, shared notes, and shouted reminders. Generic task apps treat couples as just two free users — no fairness ratio, no shared streak, no \"things they loved\" cross-feed.",
        solution: "A two-seat task OS gated to one pair via env-driven email allowlist. AI does the structuring (parse + classify + break down + nudge), Supabase Realtime does the sync, gamification (XP / streaks / levels / weekly fairness bar) does the motivation. Voice-to-task hooks the Web Speech API into the same Gemini parser.",
        outcomes: [
            "Natural-language task creation via type or voice",
            "Realtime sync between two devices via Supabase channels",
            "Routines feature with weekly grid + partner-completion trail",
            "Analytics: couple completion donut + 12-week activity heatmap + fairness bar",
            "Native Android via Capacitor sharing the same Next build",
        ],
    },
    {
        id: "006",
        slug: "leadsniper",
        title: "LeadSniper",
        description: "AI-powered lead generation engine for freelancers. Scrapes Google Places, crawls sites, scores 23 opportunity signals, drafts personalized outreach across Email / WhatsApp / LinkedIn.",
        longDescription: "LeadSniper is an end-to-end lead generation pipeline for freelancers and small agencies. A local Playwright crawler pulls businesses from Google Places, audits their sites against PageSpeed and a 23-factor scoring rubric, then Gemini 2.5 drafts channel-specific outreach. A Next.js dashboard on Supabase keeps the whole pipeline visible and operable. Splits compute between a local watch-mode scraper (free bandwidth, free RAM) and a hosted dashboard (free Vercel + Supabase tiers).",
        tech: ["Next.js 14", "TypeScript", "Supabase", "Playwright", "Gemini 2.5", "PageSpeed API"],
        metrics: [
            { label: "Scoring Factors", value: "23" },
            { label: "Channels", value: "Email · WA · LinkedIn" },
            { label: "Infra Cost", value: "$0" },
        ],
        color: "bg-acid",
        textColor: "text-ink",
        link: "https://github.com/hatimhtm/LeadSniper",
        category: "AI / ML",
        problem: "Lead generation for freelancers is a manual slog: searching directories, visiting dozens of sites, copying emails into a spreadsheet, then writing cold messages from scratch. Most tools solve one slice and cost hundreds a month.",
        solution: "Split the system into a local scraper (free compute, free bandwidth) and a hosted dashboard (free Vercel + Supabase tiers). The scraper idles in watch mode waiting for search jobs from the dashboard; the dashboard handles pipeline state, scoring, and AI drafts.",
        outcomes: [
            "Runs end-to-end on free infrastructure",
            "23-factor niche-aware opportunity scoring",
            "Channel-specific AI drafts (email · WhatsApp · LinkedIn)",
            "Watch-mode scraper with idle RAM footprint",
        ],
    },

    /* ─────────── TIER C · LIVE DEMOS — TRY IN BROWSER ─────────── */

    {
        id: "007",
        slug: "scriptdeck",
        title: "ScriptDeck",
        description: "Keyboard-first conversation script runner — 8-step decks, categorised response cards, call timer, session analytics. Offline-first PWA.",
        longDescription: "ScriptDeck is a keyboard-driven runner for scripted conversations (sales, support, onboarding). Walk a multi-step script while categorised response cards sit on the right rail, ready for the moment a prospect throws an objection. A call timer auto-starts, per-step time is logged, and the analytics modal shows where the conversation actually got stuck.",
        tech: ["Vite 6", "Vanilla JS", "PWA", "Service Worker", "localStorage"],
        metrics: [
            { label: "Steps", value: "8" },
            { label: "Response Cards", value: "11" },
            { label: "Backend", value: "None" },
        ],
        color: "bg-electric",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/ScriptDeck",
        liveDemo: "https://hatimhtm.github.io/ScriptDeck/",
        category: "Web App",
        problem: "Sales scripts live in Google Docs and cmd-F is the rebuttal lookup. Existing CRM-attached tools either chain you to a subscription or expect you to paste your script into Notion.",
        solution: "A single-tab keyboard-driven runner. Step nav, categorised response cards, call timer, session history, analytics — all client-side, all offline-first via Service Worker, all import/exportable as a single JSON file your team can share.",
        outcomes: [
            "Keyboard-first: arrows move steps, ⌘C copies response, no mouse needed",
            "Offline-first PWA — installs on iPad and works between calls",
            "JSON + Markdown export for team distribution",
            "Custom <dialog> modal system — no native confirm()/alert() in the UX",
        ],
    },
    {
        id: "008",
        slug: "night-market-tycoon",
        title: "Night Market Tycoon",
        description: "Idle / tycoon HTML5 web game — 20 businesses, 13 upgrades, 13 achievements, prestige loop. Vanilla JS on Vite with break_eternity.js for the math.",
        longDescription: "Night Market Tycoon is a browser idle game with 20 businesses, 13 upgrades, 13 achievements, and a prestige loop at $1T total earned. ~2,000 LOC of vanilla JS on Vite, no framework, single-file production bundle, runs offline once loaded. Targets the CrazyGames / GameDistribution / Y8 portals with a 3-platform ad-SDK abstraction; source-available under PolyForm Noncommercial.",
        tech: ["Vite 7", "Vanilla JS", "break_eternity.js", "Howler.js", "Tailwind 4"],
        metrics: [
            { label: "Businesses", value: "20" },
            { label: "Achievements", value: "13" },
            { label: "Number Cap", value: "1e1000" },
        ],
        color: "bg-vivid",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/night-market-tycoon",
        liveDemo: "https://hatimhtm.github.io/night-market-tycoon/",
        category: "Web App",
        problem: "Most browser idle games are stuck on Flash-era UX or feel like ad farms. Portal operators (CrazyGames / GameDistribution) want one bundle they can host themselves, with their ad SDK baked in.",
        solution: "Pure vanilla JS on Vite — single-file build output, sub-100KB compressed. One ad-SDK abstraction targets three portals via a single constant swap. break_eternity.js handles big-number math past 1e1000. Tamper-resistant Base64+hash saves so DevTools edits fail integrity check on load.",
        outcomes: [
            "Single dist/ ships unchanged to CrazyGames / GameDistribution / Y8 / GitHub Pages",
            "20 businesses + 13 achievements + prestige loop in ~2,000 LOC",
            "Offline progress capped at 75% — active play always feels better than idling",
            "PolyForm Noncommercial licensed; live playable demo via GitHub Pages",
        ],
    },
    {
        id: "009",
        slug: "lessonforge",
        title: "LessonForge",
        description: "Offline teaching dashboard for language tutors — multi-page lessons, ⌘K palette, lesson templates, undo/redo, save indicator. PWA, zero backend.",
        longDescription: "LessonForge is a teaching dashboard for language tutors. Multi-page rich-text lessons, a built-in timer (stopwatch + countdown with Web Audio chime), student profiles, drag-and-drop reordering, a categorised toolkit of grammar / vocab / pronunciation cards, 50-step undo/redo history, ⌘K command palette across pages + cards + students, 6 starter-lesson templates, JSON + Markdown export, dark mode. Vite + vanilla JS + localStorage, full offline persistence via PWA.",
        tech: ["Vite", "Vanilla JS", "PWA", "Service Worker", "Web Audio API"],
        metrics: [
            { label: "Pages", value: "Multi" },
            { label: "Undo Steps", value: "50" },
            { label: "Backend", value: "None" },
        ],
        color: "bg-acid",
        textColor: "text-ink",
        link: "https://github.com/hatimhtm/LessonForge",
        category: "Web App",
        problem: "Most lesson-prep tools either lock you into a SaaS subscription or expect you to live inside Google Docs / Notion. Tutors need to open a tab between Zoom calls, swipe pages, hit space for the timer, scribble while the student is talking.",
        solution: "Vanilla JS app with a real undo/redo ring buffer, rich-text contenteditable bodies, and a full state-snapshot-per-action pattern. v2 added a custom <dialog> modal system, PWA, ⌘K command palette, voice-aware audio chime, and 6 starter-lesson templates.",
        outcomes: [
            "Full offline persistence — once the tab loads, no network needed",
            "Custom <dialog> modal system replaces every native confirm()/alert()",
            "⌘K palette across pages + students + toolkit cards",
            "JSON + Markdown export for share-ready lesson handouts",
        ],
    },
    {
        id: "010",
        slug: "virtual-tryon-poc",
        title: "Atelier Virtuel",
        description: "Free public AI virtual try-on demo. Upload a selfie + clothing photo, Gemini 3 Flash Image composites the result. No account, no storage, rate-limited.",
        longDescription: "A free public AI virtual try-on POC. Built as a fast iteration before the full TryIt iOS app. Two API routes (Gemini 2.5 Flash for input validation, Gemini 3 Flash Image for generation), client-side compression to dodge Vercel's 413 limit, in-memory IP rate limiting, brutalist UI in cream + ink + acid yellow. Zero database, zero account, zero photo storage.",
        tech: ["Next.js 16", "Tailwind 4", "Gemini 3 Flash Image", "Framer Motion"],
        metrics: [
            { label: "Rate Limit", value: "5/h/IP" },
            { label: "Gen Time", value: "30–45s" },
            { label: "Storage", value: "None" },
        ],
        color: "bg-acid",
        textColor: "text-ink",
        link: "https://github.com/hatimhtm/virtual-tryon-poc",
        liveDemo: "https://virtual-tryon-poc-two.vercel.app",
        category: "AI / ML",
        problem: "Before building a polished iOS app for virtual try-on, you need to validate the AI flow itself: does Gemini 3 Flash Image actually preserve the person's body and only swap the garment? Does it handle weird inputs gracefully?",
        solution: "A 4-step web POC with two AI calls (validate input → generate output), client-side compression so payloads stay small, IP rate limiting so a public link doesn't bankrupt the Gemini quota, and a brutalist UI that makes the demo feel intentional rather than throwaway.",
        outcomes: [
            "Validated the two-stage AI pipeline (cheap validation → expensive generation)",
            "Public-link-safe via IP rate limiting (5 gen/hour, 20 validations/hour)",
            "Zero storage, zero database — photos round-trip via base64 through the Gemini API",
            "Free fork-and-learn under MIT",
        ],
    },

    /* ─────────── TIER D · CLIENT WORK · RANGE ─────────── */

    {
        id: "011",
        slug: "cgs-language-services",
        title: "CGS Language Services",
        description: "Multilingual marketing site for a translation agency — EN/FR/AR/ZH document translation for Chinese university applications. React 19 + i18next with full Arabic RTL. Freelance build, shipped to Vercel.",
        longDescription: "A multilingual marketing site for CGS Language Services, an agency translating documents between English / French / Arabic / Chinese for Moroccan students applying to Chinese universities. React 19 on Vite 8, Tailwind 4, i18next with full Arabic RTL handling, Framer Motion for the editorial moments. Built as a freelance commission and shipped to production on Vercel.",
        tech: ["React 19", "Vite 8", "Tailwind 4", "i18next (RTL)", "Framer Motion"],
        metrics: [
            { label: "Locales", value: "EN · FR · AR · ZH" },
            { label: "RTL", value: "Full Arabic" },
            { label: "Status", value: "Live" },
        ],
        color: "bg-hotpink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/cgs-language-services",
        liveDemo: "https://cgs-language-services.vercel.app",
        category: "Web",
        problem: "Translation agencies in this niche pitch to families of Moroccan students who switch fluidly between French, Arabic, and Mandarin. A French-only marketing site loses every parent who reads the brochure in Arabic and every administrator who only opens the Mandarin tab.",
        solution: "i18next handling 4 locales with first-class RTL for Arabic — not just a translation layer but a layout-aware locale system. Framer Motion carries the editorial photography. Vite 8 keeps the production build sub-200KB.",
        outcomes: [
            "Four-locale production marketing site shipped to Vercel",
            "Full Arabic RTL with layout-aware components",
            "Freelance client work — kept public as a portfolio piece",
        ],
    },
    {
        id: "012",
        slug: "china-global-study",
        title: "China Global Study CRM",
        description: "Internal student-placement CRM for an agency placing Moroccan students into Chinese universities. Next.js 16 + Supabase + 8-stage drag-and-drop kanban + 5 themes. Freelance, in production.",
        longDescription: "An internal student-placement CRM built for China Global Study, the parent agency behind CGS Language Services. Next.js 16 + Supabase, an 8-stage kanban that drag-and-drops applicants between funnel stages (initial enquiry → document collection → translation → application → admission → visa → departure → enrolled), 5 themes, and a clean role-gated authentication model. Built as a freelance commission and running in production.",
        tech: ["Next.js 16", "Supabase", "TypeScript", "DnD Kit", "Framer Motion"],
        metrics: [
            { label: "Funnel Stages", value: "8" },
            { label: "Themes", value: "5" },
            { label: "Status", value: "Production" },
        ],
        color: "bg-vivid",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/china-global-study",
        liveDemo: "https://dashboard-omega-blue-41.vercel.app",
        category: "Web App",
        problem: "Student-placement agencies live in spreadsheets — every applicant means one tab, every stage transition means a manual cell update, and a missed deadline can mean a student loses their visa window.",
        solution: "An 8-stage drag-and-drop kanban that turns the agency's actual workflow into a visible pipeline. Supabase backs the data, Next.js 16 renders the UI server-side, five themes let the agency match the look to client-presentation contexts.",
        outcomes: [
            "Replaced a multi-tab spreadsheet workflow with a single pipeline view",
            "Drag-and-drop stage transitions with optimistic UI",
            "Freelance client work — in production for the agency",
        ],
    },
    {
        id: "013",
        slug: "lumi",
        title: "Lumi",
        description: "A private cinema for two. AI-tuned daily-refreshing feed of movie + TV picks, shared with one partner. Supabase + Gemini + TMDB. Two-seat gate.",
        longDescription: "Lumi is a couple's movie recommendation system. Reads both partners' rating histories from Supabase, asks Gemini 2.5 to write smart category rows that account for what both have already seen, lets each partner veto a candidate from a Tonight's Pick stack, refreshes the whole feed at 05:00 UTC every day via Vercel cron. Once one partner rates a movie 4.5★+, it surfaces in the other's \"things they loved\" row.",
        tech: ["Next.js 16", "Supabase", "Gemini 2.5", "TMDB v4", "Tailwind 4", "Vercel Cron"],
        metrics: [
            { label: "Mode", value: "Two-seat" },
            { label: "Refresh", value: "05:00 UTC daily" },
            { label: "License", value: "Read-only" },
        ],
        color: "bg-electric",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/lumi-movie-night",
        private: true,
        category: "AI / ML",
        problem: "Most recommendation engines aim wide — they want a billion users in a content carousel, which is why one Ghibli movie gets you twelve Pixar suggestions. Couples want the smaller problem: two people, one couch, one shared evening.",
        solution: "A two-seat app that reads both rating histories, asks Gemini to name 10 category rows accounting for what both have seen, and surfaces \"things they loved you haven't seen\" cross-feed. Spotify-Wrapped-style end-of-year recap turns the year of ratings into stories cards. Personal data env-gated so source is publishable read-only.",
        outcomes: [
            "Two-seat gate pattern — only emails in AUTHORIZED_EMAILS can sign in",
            "Vercel cron refreshes the joint feed at 05:00 UTC daily",
            "Tonight's Pick Together — three candidates, each partner gets one veto",
            "Wrapped-style end-of-year stories card view",
        ],
    },
    {
        id: "014",
        slug: "rudratek-dashboard",
        title: "Rudratek Dashboard",
        description: "Premium project-operations dashboard. 12 mock projects, status donut, activity feed, drillable side panel, analytics page. Zero chart libraries — every viz hand-rolled SVG.",
        longDescription: "Rudratek Dashboard started as an interview deliverable. The v2 overhaul went from generic admin look to a real product: Next.js 14 + TypeScript + Tailwind, hand-rolled SVG visualisations (sparkline, status donut, weekday heatmap, fairness bar, progress bar — all under 60 LOC each, zero chart-lib deps), an analytics page with revenue trend + top-clients ranking + priority distribution, and a drillable side panel with milestones timeline, task checklist, team grid, project sparkline.",
        tech: ["Next.js 14", "TypeScript", "Tailwind v4", "Lucide", "Framer Motion"],
        metrics: [
            { label: "Mock Projects", value: "12" },
            { label: "Viz Primitives", value: "5" },
            { label: "Chart Libs", value: "0" },
        ],
        color: "bg-vivid",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/rudratek-dashboard",
        category: "Web App",
        problem: "The v1 interview deliverable shipped working but felt generic — 3 flat stat cards on a project table, no charts, no progress bars, no team avatars. Plus a font bug: globals.css had a stray `font-family: Arial` overriding the next/font Inter import.",
        solution: "v2 fixed the font bug, switched to an indigo→violet accent system applied across nav + focus rings + KPI icons + sparklines, expanded the Project type from 7 fields to 14 (added team, milestones, tasks, tags, revenueTrend), built 5 hand-rolled SVG viz primitives in ~250 LOC total, added a new /analytics page.",
        outcomes: [
            "Zero chart libraries — every visualisation hand-rolled SVG",
            "Project type expanded 7 → 14 fields with realistic mock data",
            "New /analytics page with burn-rate / at-risk-project KPIs",
            "CI workflow gates typecheck + lint + build on every push",
        ],
    },
    {
        id: "015",
        slug: "echoscribe",
        title: "EchoScribe",
        description: "Audio → Whisper → structured meeting intelligence → Slack / Markdown / JSON. One OpenAI key. CLI + FastAPI server + directory watcher. Python 3.10+.",
        longDescription: "EchoScribe automates the meeting-to-Slack-digest workflow. Pull audio from a recording source, transcribe via Whisper, run a multi-step summarisation chain (decisions, action items, sentiment, follow-ups), and post a structured digest to Slack, Markdown, or JSON. Ships as a Python CLI, a FastAPI server, and a directory watcher — one OpenAI key powers all three. Docker image on GHCR.",
        tech: ["Python 3.10+", "OpenAI Whisper", "GPT-4o", "FastAPI", "Docker", "Slack SDK"],
        metrics: [
            { label: "Surfaces", value: "CLI · API · Watcher" },
            { label: "Outputs", value: "Slack / MD / JSON" },
            { label: "Container", value: "GHCR" },
        ],
        color: "bg-hotpink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/EchoScribe",
        category: "AI / ML",
        problem: "Every meeting has 30 minutes of decisions and 5 hours of context. Good written summaries take humans 20 minutes to compose — and they always wait until morning, after the team has already moved on.",
        solution: "A pipeline that runs the moment the recording ends. Whisper for transcription, a multi-step GPT-4o chain that extracts decisions / action items / follow-ups into a structured JSON schema, then renders Slack-friendly markdown. Ships as a CLI, a FastAPI server, and a directory watcher — pick the surface that fits the team.",
        outcomes: [
            "End-to-end: audio file → Slack message in ~3 minutes",
            "Structured-output prompts (no markdown drift across runs)",
            "Three deployment surfaces from one codebase (CLI, server, watcher)",
            "Container image published on GHCR for one-line ops deploys",
        ],
    },
    {
        id: "016",
        slug: "infinitecs",
        title: "InfiniteCS Website",
        description: "Enterprise BPO marketing site. Glassmorphism, GSAP animations, testimonials, FAQ — built for a prospect that backed out. Kept as a polished portfolio piece.",
        longDescription: "A premium one-page marketing site for Infinite Contact Solutions, a BPO operator. Custom animated hero, testimonials carousel, FAQ accordion, GSAP-driven scroll cinematography, mobile-first responsive layout, and meticulous attention to typographic rhythm. Built fast so the prospect could see the work before committing; they backed out, but the build was good enough to keep as a portfolio piece.",
        tech: ["GSAP", "Tailwind", "Glassmorphism", "Inter font"],
        metrics: [
            { label: "Vertical", value: "BPO Enterprise" },
            { label: "Status", value: "Portfolio piece" },
        ],
        color: "bg-electric",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/InfiniteCS-Website",
        category: "Web",
        problem: "BPO operators usually market with WordPress templates that scream \"call centre.\" The brief: a premium B2B marketing site that an enterprise procurement team would take seriously.",
        solution: "Editorial layout, custom typographic hierarchy, GSAP-driven scroll moments, glassmorphism cards, FAQ that pre-empts the actual procurement objections. Built fast so the prospect could see the work before committing.",
        outcomes: [
            "Premium feel without a paid template — every animation custom",
            "Mobile-first responsive — looks good on the deck-on-an-iPad demo",
            "Kept as a portfolio piece showcasing landing-page craft",
        ],
    },
    {
        id: "017",
        slug: "click2minimize",
        title: "Click2Minimize",
        description: "macOS menu-bar utility — click an app's dock icon to minimise its windows. Swift + AppKit + Accessibility API. Source-available.",
        longDescription: "A focused macOS utility that adds the missing behaviour: clicking an app's dock icon minimises all its windows instead of bringing them forward. Swift + AppKit using the macOS Accessibility API. Single-purpose, well under 1k LOC, signed and notarised. Released via the standard menu-bar agent pattern.",
        tech: ["Swift", "AppKit", "Cocoa", "macOS Accessibility API"],
        metrics: [
            { label: "Type", value: "Menu-bar agent" },
            { label: "License", value: "PolyForm NC" },
        ],
        color: "bg-ink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/Click2Minimize",
        liveDemo: "https://github.com/hatimhtm/Click2Minimize/releases/latest",
        category: "macOS",
        problem: "macOS dock-icon clicks bring an app's windows forward; there's no built-in way to make the click minimise them instead. Some workflows want the inverse — \"if it's already visible, hide it.\"",
        solution: "A menu-bar agent that intercepts dock-icon clicks via the macOS Accessibility API and toggles minimise/restore based on current window state. Signed and notarised for distribution outside the Mac App Store.",
        outcomes: [
            "Single-purpose tool that does exactly one thing well",
            "Native AppKit footprint, signed + notarised, published releases",
        ],
    },
    {
        id: "018",
        slug: "fortress",
        title: "Fortress",
        description: "Cryptographically secure password / passphrase / PIN generator. EFF Diceware (7,776 words), HIBP breach lookup, entropy + crack-time analysis, clipboard auto-clear. CLI + FastAPI + Docker.",
        longDescription: "Fortress is a focused secret-generation tool. Generates passwords + passphrases + PINs with EFF Diceware (the 7,776-word list designed for memorable + secure passphrases), checks output against the HIBP breach corpus before returning, computes entropy and multi-scenario crack-time estimates, and auto-clears the clipboard after 30 seconds. Ships as a Python 3.10+ CLI, a FastAPI HTTP API, and a Docker image on GHCR.",
        tech: ["Python 3.10+", "FastAPI", "EFF Diceware", "HIBP API", "Docker", "GHCR"],
        metrics: [
            { label: "Diceware Words", value: "7,776" },
            { label: "Breach Check", value: "HIBP" },
            { label: "Surfaces", value: "CLI · API · Docker" },
        ],
        color: "bg-acid",
        textColor: "text-ink",
        link: "https://github.com/hatimhtm/Fortress",
        liveDemo: "https://pypi.org/project/fortress/",
        category: "CLI",
        problem: "Password generators on the web are slow, ad-laden, and require trusting a stranger's server. Local tools like `pwgen` are blunt — no breach check, no entropy reporting, no Diceware support, no clipboard auto-clear.",
        solution: "A focused Python tool that does all of the above in one CLI + one HTTP API. EFF Diceware for memorable passphrases, HIBP for breach intelligence, mathematically grounded entropy + crack-time analysis, clipboard auto-clear so the secret doesn't linger in shell history.",
        outcomes: [
            "Published on PyPI — `pip install fortress`",
            "Three deployment surfaces from one codebase (CLI, FastAPI, Docker)",
            "HIBP breach lookup integrated into the generation flow",
            "Open-source, MIT licensed",
        ],
    },
    {
        id: "019",
        slug: "freelane",
        title: "Freelane",
        description: "Personal freelance ledger — clients, projects, payments, expenses, invoices, multi-currency, French-first PDF generation. Next.js 16 + Supabase. Source-available showcase, not a product.",
        longDescription: "Freelane is a single-user freelance accounting ledger built for personal use. Tracks clients, projects, payments, expenses, generates French-first invoice PDFs, handles multi-currency conversion, and surfaces the metrics that actually matter (revenue YTD, average project size, payment-cycle length). Next.js 16 + Supabase + Tailwind 4. Source-available as a showcase, not a product.",
        tech: ["Next.js 16", "Supabase", "Tailwind 4", "Framer Motion"],
        metrics: [
            { label: "Mode", value: "Single-user" },
            { label: "Invoices", value: "FR-first PDF" },
            { label: "Currency", value: "Multi" },
        ],
        color: "bg-hotpink",
        textColor: "text-cream",
        link: "https://github.com/hatimhtm/freelane",
        liveDemo: "https://freelane-wine.vercel.app",
        category: "Web App",
        problem: "Generic freelance accounting tools (Bonsai, Wave, FreshBooks) charge per month for what is, structurally, a spreadsheet with a payment-cycle reminder. As a French freelancer, none of them handle French invoice PDF requirements out-of-the-box.",
        solution: "A single-user Next.js + Supabase build with PDF generation tuned to French invoice format, multi-currency conversion, and a dashboard that surfaces the metrics that actually inform pricing decisions. Open-source as a showcase, not a product.",
        outcomes: [
            "French invoice PDF generation",
            "Multi-currency revenue tracking with FX conversion",
            "Single-user — no team features, no per-seat billing",
            "Shipped to Vercel as a live demo",
        ],
    },
];

export function getProjectBySlug(slug: string): Project | undefined {
    return projects.find((p) => p.slug === slug);
}
