#!/usr/bin/env python3
"""Scan public/work and public/icons and write lib/media.generated.ts.

public/work/<slug>.jpg            cover (1600x1000)
public/work/<slug>-2.jpg, -3.jpg  more edited shots
public/work/<slug>-night.jpg      dark-mode cover (optional)
public/work/<slug>.mp4            trailer, with <slug>-poster.jpg
public/icons/<slug>.webp          app icon
"""
import json, pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
work, icons = root / "public" / "work", root / "public" / "icons"
media = {}
for f in sorted(work.iterdir()):
    m = re.match(r"^(.+?)(-night|-poster|-(\d+))?\.(jpg|png|webp|mp4)$", f.name)
    if not m or f.name.startswith(("hero-", "screens-wall")) or re.search(r"-(screen|desktop|mobile|mac)(-\d+)?\.", f.name):
        continue
    slug, suffix, n, ext = m.group(1), m.group(2) or "", m.group(3), m.group(4)
    e = media.setdefault(slug, {})
    url = "/work/" + f.name
    if ext == "mp4":
        e["trailer"] = url
    elif suffix == "-poster":
        e["poster"] = url
    elif suffix == "-night":
        e["night"] = url
    elif n:
        e.setdefault("shots", []).append((int(n), url))
    else:
        e["cover"] = url
for f in sorted(icons.glob("*.webp")):
    media.setdefault(f.stem, {})["icon"] = "/icons/" + f.name
for e in media.values():
    if "shots" in e:
        e["shots"] = [u for _, u in sorted(e["shots"])]
out = "// Generated by scripts/sync_media.py from public/work and public/icons. Do not edit by hand.\n"
out += "export type Media = { cover?: string; night?: string; shots?: string[]; trailer?: string; poster?: string; icon?: string };\n"
out += "export const MEDIA: Record<string, Media> = " + json.dumps(media, indent=4) + ";\n"
(root / "lib" / "media.generated.ts").write_text(out)
print("media for", len(media), "projects:", ", ".join(sorted(media)))
